# Site settings
title: Poppy Project
# url: http://poppy-project.github.io
baseurl: /poppy-project.org

description:
  en: >-
    Poppy Project website.
    You will love it.
  fr: >-
    Site du Projet Poppy.

outlinks:
  en:
    - url: https://forum.poppy-project.org
      title: Forum
    - url: http://docs.poppy-project.org/en/
      title: Documentation
  fr:
    - url: https://forum.poppy-project.org
      title: Forums
    - url: http://docs.poppy-project.org/fr/
      title: Documentation


# Build settings
markdown: kramdown
highlighter: rouge

timezone: Europe/Paris

sass:
  style: compressed

include: [ "_pages" ]

exclude: [
  "bower_components",
  "vendor",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

permalink: /:categories/:title
default_lang: en

languages:
  - name: English
    key: en
  - name: Fran√ßais
    key: fr

# Will be overridden by github
github:
  repository_url: https://github.com/poppy-project/poppy-project.org
